CADDY_HTTPS_PORT: 8443
CADDY_HTTP_PORT: 8090
CMS_HOST: studio.echiphub.in
CONTACT_EMAIL: contact@edx.echiphub.in
ENABLE_ACCOUNT_ACTIVATION: false
ENABLE_HTTPS: true
ENABLE_THIRD_PARTY_AUTH: true
ENABLE_WEB_PROXY: false
ID: rRYnEgPaVxDEO7LLLkwEBoR1
INDIGO_PRIMARY_COLOR: '#1a3c6e'
INDIGO_SECONDARY_COLOR: '#f5a623'
INDIGO_THEME_NAME: indigo

  MIIEowIBAAKCAQEAmKz0NO1NqWudsY1c0z1o4trESJ2Uv83cBE9rAbn7UJr1PeYd

  bN0BYUzwbb/bw8nmyesk9KWzBD7fKLGUZvt2cj87cnSjV79L7saZXMApWPnOwu0X

  N+/SAhnZ3wW2gTbML4GanAy4R1NNAKBWzEOWgda/qtQ9dZtRjvAFq88HxaTpUOwh

  ca5gO5yVWNWi1rRAJ3GXSP9dEFe8KxwdWGYDAEAlU52Fz+IFXwo/2S9j/FFwAQWg

  UNMd+lQ4HjczXbK+77tagm4k8/7tNRtd2PKdYg1OTUTn3XXeYKM3OuulCSkYYUnk

  Iq/rzk7+ZlaBQOOcaoD8+fGxMQshox4TK6hZfQIDAQABAoIBAAQor/VSIouzLgZE

  aMsrUNRfK7ojqsXnzG7EoBBZud4Z/oS7ZEFPKua04xbGQ20LrrEA6g6NBfmfYdJY

  tgdxIaqejNbDFSECicW9HLfhVy8AjRCTx05jhse+Xwg7flt6O+kuYWEPWqS8wOv7

  simZzLuIN0vmwK7XtorLgIgL2XUZjF+Sy93ODwIp5oXAy/vBaL8KMJ2EA1re7RP8

  KyLY5G5wASSqxm2B0cocMHFM0UnKa64OhoItdtbhQ1jXaWks+rsz+96NM3l1LwDQ

  IYk5uff4khATgUkt2hOCd7ZJAfHSg2g+xhK93uRRo7A5aizEC9Ia0NoG2wgWzqN6

  xwlquDECgYEAteT/8zscgzhRRLviLUcE9U7/L+LQHmuSQXqhBRa8hA/4l+LZAqTn

  Zq0wYlUwypheWEZZnWGpTWFGp8y/Tr/7UXq5xZ1BmiwQH8OXSIikwa3DU0sSdG/u

  F/6wQuPYtevK9nHyC2e82aLPwpqRJQr36NJQPoCxe+L6f2Gd5DfwYFECgYEA1uCE

  HlpuCnAcJXbefULpMFMGXh7coWzXjf0y6aZuMmy4wMm4tFAMLexArHB9tU0w7940

  ewAWj7J0mRYZwJxetr4kz6WsvE1ONAJBmrrGWxWdQO335JPnvig5sHDs+PY57Xx0

  uzlcvFHHk5MdPcjV212X0Sx3uv63uw7t6nOzJ20CgYBMBbUP9LG7Cku1HY2vfNJO

  sMCpQ/PV8wHCyj0IQnNyArbUzGQE3eU1HcduIcrtsfckj+qeg5XeGH0OXt3KTST9

  7fw84rfrduUaUYYmM64goL5VTrgc4Dcz4ifLHS2TA0Tl8cPHDol4sLqCzFVDlSz+

  KwCMzv7fF4O4v5TdMKAPsQKBgQC4FH8awb2jk4eJUNwp0ziR/Y5m82lvoR7ItTD4

  mWuuJxXfkvB5CFpmvQ5qq7QFratO0r2C4gBx+h+JRjWpnExHoX1HplbkuhVU2Nn7

  BCcJwOqGxVaoq0zMywkg7p0Ua1wU55nZCrs3WZfwBQf39iW/V97Hg6DOwYgE6DVJ

  tPS1wQKBgD/zpJhI/i9UTq6vrQYmG6RXD8kscXMDt0minFnd2UwKX6I9ti35a8Vp

  Uhzbq1BEUSC3DkUIBZEgp2c2hWEk/utW7ZaDcu4kVlXLv0tSJ6WpQvvb+VNqZDeM

  g6vBP+grosM8PoTALZYyGmJK+3hE427Ke3GsPLDYcVb5Zy39EOH2

  -----END RSA PRIVATE KEY-----'
LANGUAGE_CODE: en
LMS_HOST: edx.echiphub.in
MAX_ASSET_UPLOAD_FILE_SIZE_IN_MB: 1000
OPENEDX_EXTRA_SETTINGS:
  FEATURES:
    ENABLE_COMBINED_LOGIN_REGISTRATION: true
    ENABLE_THIRD_PARTY_AUTH: true
  SOCIAL_AUTH_REDIRECT_IS_HTTPS: true
  THIRD_PARTY_AUTH_BACKENDS:
  - social_core.backends.keycloak.KeycloakOAuth2
PLATFORM_NAME: Edtech
PLUGINS:
- indigo
- keycloak_sso
- mfe
PLUGIN_INDEXES:
- https://overhang.io/tutor/main
- https://overhang.io/tutor/contrib
REGISTRATION_REQUIRE_EMAIL_VALIDATION: false
SESSION_COOKIE_DOMAIN: .echiphub.in
SMTP_HOST: email-smtp.ap-south-1.amazonaws.com
SMTP_PORT: 587
SMTP_USERNAME: AKIAYYAFYCYSFWUALXVN
SMTP_USE_SSL: false
SMTP_USE_TLS: true
