SITE_NAME: "studio.echiphub.in"
BOOK_URL: ""
LOG_DIR: "/openedx/data/logs"
LOGGING_ENV: "sandbox"
OAUTH_OIDC_ISSUER: "https://edx.echiphub.in/oauth2"
PLATFORM_NAME: "Edtech"
FEATURES:
  
  
  CERTIFICATES_HTML_VIEW: true
  PREVIEW_LMS_BASE: "preview.edx.echiphub.in"
  ENABLE_CSMH_EXTENDED: false
  ENABLE_LEARNER_RECORDS: false
  ENABLE_LIBRARY_INDEX: true
  MILESTONES_APP: true
  ENABLE_PREREQUISITE_COURSES: true
LMS_ROOT_URL: "https://edx.echiphub.in"
CMS_ROOT_URL: "https://studio.echiphub.in"
CMS_BASE: "studio.echiphub.in"
LMS_BASE: "edx.echiphub.in"
CONTACT_EMAIL: "contact@edx.echiphub.in"
CELERY_BROKER_TRANSPORT: "redis"
CELERY_BROKER_HOSTNAME: "redis:6379"
CELERY_BROKER_VHOST: "0"
CELERY_BROKER_USER: ""
CELERY_BROKER_PASSWORD: ""
ALTERNATE_WORKER_QUEUES: "lms"
ENABLE_COMPREHENSIVE_THEMING: true
EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST: "email-smtp.ap-south-1.amazonaws.com"
EMAIL_PORT: 587
EMAIL_USE_TLS: true
HTTPS: "on"
LANGUAGE_CODE: "en"
SESSION_COOKIE_DOMAIN: "studio.echiphub.in"

SECRET_KEY: "hxw49khrAC9N6rAaur5iZSZ2"
AWS_ACCESS_KEY_ID: ""
AWS_SECRET_ACCESS_KEY: ""
DOC_STORE_CONFIG: null
XQUEUE_INTERFACE:
  django_auth: null
  url: null
DATABASES:
  default:
    ENGINE: "django.db.backends.mysql"
    HOST: "mysql"
    PORT: 3306
    NAME: "openedx"
    USER: "openedx"
    PASSWORD: "zD8ubeOF"
    ATOMIC_REQUESTS: true
    OPTIONS:
      init_command: "SET sql_mode='STRICT_TRANS_TABLES'"
      charset: "utf8mb4"
EMAIL_HOST_USER: "AKIAYYAFYCYSFWUALXVN"
EMAIL_HOST_PASSWORD: "BMskPARejS/NCRxos+uoxMkxJmSVFz8AaqWLJAWK0+vL"
