SITE_NAME: "edx.echiphub.in"
BOOK_URL: ""
LOG_DIR: "/openedx/data/logs"
LOGGING_ENV: "sandbox"
OAUTH_OIDC_ISSUER: "https://edx.echiphub.in/oauth2"
PLATFORM_NAME: "Edtech"
FEATURES:
  
  
  CERTIFICATES_HTML_VIEW: true
  PREVIEW_LMS_BASE: "preview.edx.echiphub.in"
  ENABLE_CSMH_EXTENDED: false
  ENABLE_COMBINED_LOGIN_REGISTRATION: true
  ENABLE_GRADE_DOWNLOADS: true
  ENABLE_LEARNER_RECORDS: false
  ENABLE_MOBILE_REST_API: true
  ENABLE_OAUTH2_PROVIDER: true
  ENABLE_PREREQUISITE_COURSES: true
  ENABLE_THIRD_PARTY_AUTH: true
  MILESTONES_APP: true
  ENABLE_SUBSECTION_GATING: true
LMS_ROOT_URL: "https://edx.echiphub.in"
CMS_ROOT_URL: "https://studio.echiphub.in"
CMS_BASE: "studio.echiphub.in"
LMS_BASE: "edx.echiphub.in"
CONTACT_EMAIL: "contact@edx.echiphub.in"
CELERY_BROKER_TRANSPORT: "redis"
CELERY_BROKER_HOSTNAME: "redis:6379"
CELERY_BROKER_VHOST: "0"
CELERY_BROKER_USER: ""
CELERY_BROKER_PASSWORD: ""
ALTERNATE_WORKER_QUEUES: "cms"
ENABLE_COMPREHENSIVE_THEMING: true
EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST: "email-smtp.ap-south-1.amazonaws.com"
EMAIL_PORT: 587
EMAIL_USE_TLS: true
ACE_ROUTING_KEY: "edx.lms.core.default"
HTTPS: "on"
LANGUAGE_CODE: "en"
SESSION_COOKIE_DOMAIN: "edx.echiphub.in"

SECRET_KEY: "hxw49khrAC9N6rAaur5iZSZ2"
AWS_ACCESS_KEY_ID: ""
AWS_SECRET_ACCESS_KEY: ""
DOC_STORE_CONFIG: null
XQUEUE_INTERFACE:
  django_auth: null
  url: null
DATABASES:
  default:
    ENGINE: "django.db.backends.mysql"
    HOST: "mysql"
    PORT: 3306
    NAME: "openedx"
    USER: "openedx"
    PASSWORD: "zD8ubeOF"
    ATOMIC_REQUESTS: true
    OPTIONS:
      init_command: "SET sql_mode='STRICT_TRANS_TABLES'"
      charset: "utf8mb4"
EMAIL_HOST_USER: "AKIAYYAFYCYSFWUALXVN"
EMAIL_HOST_PASSWORD: "BMskPARejS/NCRxos+uoxMkxJmSVFz8AaqWLJAWK0+vL"

# --- Keycloak OIDC (python-social-auth) ---
THIRD_PARTY_AUTH_BACKENDS:
  - social_core.backends.keycloak.KeycloakOAuth2

SOCIAL_AUTH_KEYCLOAK_KEY: "openedx"
SOCIAL_AUTH_KEYCLOAK_SECRET: "3Iamm9L61VcN06Av5qp9hqGZBd4lplBt"
SOCIAL_AUTH_KEYCLOAK_AUTHORIZATION_URL: "https://sso.echiphub.in/realms/platform/protocol/openid-connect/auth"
SOCIAL_AUTH_KEYCLOAK_ACCESS_TOKEN_URL: "https://sso.echiphub.in/realms/platform/protocol/openid-connect/token"
SOCIAL_AUTH_KEYCLOAK_USERINFO_URL: "https://sso.echiphub.in/realms/platform/protocol/openid-connect/userinfo"
SOCIAL_AUTH_REDIRECT_IS_HTTPS: true
SOCIAL_AUTH_KEYCLOAK_END_SESSION_URL: "https://sso.echiphub.in/realms/platform/protocol/openid-connect/logout"
IDA_LOGOUT_URI_LIST:
  - "https://hub.echiphub.in/hub/logout"
  - "https://www.echiphub.in/?kc_slo=1&t=ucPvC2AudPUJHnnBJNyU2S2AmAN1r31MaqYAx5n505L5gF7XwAgMNMdlHdlHlrrT"
  - "https://events.echiphub.in/logout/"
SOCIAL_AUTH_KEYCLOAK_SUPERUSER_ROLES:
  - "wp_admin"
SOCIAL_AUTH_KEYCLOAK_STAFF_ROLES:
  - "wp_admin"
SOCIAL_AUTH_KEYCLOAK_SUPERUSER_ROLES:
  - "wp_admin"
SOCIAL_AUTH_KEYCLOAK_STAFF_ROLES:
  - "wp_admin"
